spring:
  application:
    name: Test

# AWS
# ADD YOUR CREDENTIALS HERE FOR ACCESSING S3 BUCKET
aws:
  s3:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    bucket: ${S3_BUCKET}
    region: ${AWS_REGION}
